# Generated by Django 4.1.4 on 2022-12-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numbofpages',
            new_name='number_of_pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
