# Generated by Django 4.1.3 on 2022-12-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='student1',
        ),
    ]
