# Generated by Django 4.1.3 on 2022-12-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_rename_student_student1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student1',
            new_name='student',
        ),
    ]
