# Generated by Django 4.1.3 on 2022-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.IntegerField(default='10', max_length=10),
        ),
    ]
